### ISSUE TITLE
README中的Cat021测试数据有问题吧

### ISSUE THREAD

**Issue by horrzs** [Sadness96/AnalysisCat#1]
这个项目内的readme中提供了测试数据：

##### 报文密文
``` txt
15002efba1df80000100302327660055a0b60144ae0a7802610006080388000a077e043e0d33b3c72de000800002
```

##### 报文解析
``` json
{
    "I021/030":"2021/1/22 4:59:58.796",
    "I021/130":[
        114.145255647124,
        30.103515219435998
    ],
    "I021/080":"780261",
    "I021/157":62.5,
    "I021/170":"CSN3127 "
}
```

提供的这串数据是错的吧？？？根本解析不出来啊
通过`AsterixInspector`程序解析得到的结果。
![image](https://github.com/user-attachments/assets/6d8d08c4-b603-4319-b6cf-bc13be76ab5a)
![image](https://github.com/user-attachments/assets/86cb3f82-9d06-44b1-a654-3ff10df7aa6e)
该程序已经由 @mengps 封装为DLL动态库的形式。[mengps/AsterixParser](https://github.com/mengps/AsterixParser)

**Comment by mengps** [comment]
数据有问题，wireshark结果一样。
![image](https://github.com/user-attachments/assets/d4f2ca96-feee-4b04-bbbc-27344e64ba13)

**Comment by horrzs** [comment]
> 直接用这个吧，功能很全面，可靠性也很高。[mengps/AsterixParser](https://github.com/mengps/AsterixParser)

**Comment by horrzs** [comment]
> 数据有问题，wireshark结果一样。 ![image](https://private-user-images.githubusercontent.com/33405710/378894261-d4f2ca96-feee-4b04-bbbc-27344e64ba13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NTQ3MTMsIm5iZiI6MTcyOTc1NDQxMywicGF0aCI6Ii8zMzQwNTcxMC8zNzg4OTQyNjEtZDRmMmNhOTYtZmVlZS00YjA0LWJiYmMtMjczNDRlNjRiYTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDA3MjAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjZmFjNmY3NmUwMmVmYjdmNjU3N2E1OGI2ZjY4MDkzODUxNjUyZWY3OGFmNDQ4MWVlODdiMGU2Y2Q1ODE5ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ca4MPrv4FKyuvDQzwb7bRCmLUXLCsE9hyMpD9D4yfY8)

直接用这个吧，功能很全面，可靠性也很高。[mengps/AsterixParser](https://github.com/mengps/AsterixParser)

**Comment by Sadness96** [comment]
这个问题是由于协议的版本不同导致的，我没有对同类型多个版本做兼容，但是把一些常用版本的配置文件都写好了，可以修改 GetCatConfigFile 类下的字典 DicConfigCatFilePath 中 CatType.Cat021 值 "Cat021pt12ed24.xlsx" 改为 "Cat021p12ed026.xlsx"，就可以把上边的数据解析正确了。
我也注意到 AsterixInspector 和 AsterixParser 了，是不错的项目，里边的配置文件比我整理的更详细，后续我有时间的话也会在优化一下。
